---
functional:
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
implicit:
- При смене на русский язык, сайт должен быть полностью на русском языке, в том числе название товара и его описание
- Кнопки "В корзину" на всех карточках товаров должны быть с одинаковыми отступами и одинакового размера
- Если в корзине несколько товаров, то число заказываемых товаров, зачёркнутая цена, кнопка "Удалить" и исходная цена должны быть на одном уровне с последующими товарами
